### ISSUE TITLE
关于css层叠上下文，层叠顺序的一个案例分析

### ISSUE THREAD

**Issue by yukinotech** [yukinotech/blog#1]
##### 该文章的理解纯属个人理解，如有误请及时留言，或联系作者，方便改正，谢谢。

介绍css层叠上下文文档和文章很多，不了解的同学可以下面链接，进行了解：

[MDN - The stacking context
](https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context)

[张鑫旭 - 深入理解CSS中的层叠上下文和层叠顺序 ](https://www.zhangxinxu.com/wordpress/2016/01/understand-css-stacking-context-order-z-index/)

[彻底搞懂CSS层叠上下文、层叠等级、层叠顺序、z-index](https://juejin.im/post/5b876f86518825431079ddd6)

那么接下来讲一个我自己看到的一个案例，及其理解

css代码
```css
.xx{
  /* opacity: .99;  */
}

.red, .green, .blue {
  position: absolute;
  width: 100px;
  color: white;
  line-height: 100px;
  text-align: center;
}

.red {
  z-index: 1;
  top: 20px;
  left: 20px;
  background: red;
}
.green {
  top: 60px;
  left: 60px;
  background: green;
}

.blue {
  top: 100px;
  left: 100px;
  background: blue;
}
.cccc{
    height: 100px;
    width: 100px;
    background: #000;
}
```
html代码
```html
<div class="cccc">ccccc</div>
<div class="xx">
  <div class="red">Red</div>
</div>
<div class="green">Green</div>
<div class="blue">Blue</div>
```

效果如下：

![效果图](https://user-gold-cdn.xitu.io/2019/3/12/1696fc8c6f9662af?w=429&h=297&f=png&s=3499)

我们来分析一下这个案例，先引用一张图片说明层叠顺序。为方便表述，从紫色到红色，命名一个层叠顺序级别1-7。比如，图中红色`z-index>0`的，我们称层叠顺序为7。

![层叠顺序图片](https://user-gold-cdn.xitu.io/2019/3/12/1696fcc092116ae8?w=768&h=383&f=webp&s=8584)

黑色的div块是正常的文档流，也就是说是没有层叠上下文的block块。它对应的父层叠上下文是html根元素。那么它的层叠顺序应该是3。之所以写这个block模块是想以它为参考。

然后根据DOM文档顺序，接下来看red，green，blue块。

red块有`position: absolute`和`z-index:1`,创建了层叠上下文，并且层叠顺序上属于7。

green块有`position: absolute`，但是`z-index:auto`为默认值，是没有创建层叠上下文的，所以层叠顺序为6。

同理blue块的层叠顺序为6。

那我们看一下现在的层叠上下文和层叠顺序:

 - html根层叠上下文
   - black普通block块，层叠顺序为3
   - red层叠上下文，层叠顺序为7
   - green绝对定位块，无层叠上下文，层叠顺序为6
   - blue绝对定位块，无层叠上下文，层叠顺序为6
 
和效果图是不是一样？

我们改改css代码,给red块的父元素（div）增加一个opacity不为1的属性。
```css
.xx{
  opacity: .99; 
}
```

让我们来看看新的效果：

![更改css后的效果图](https://user-gold-cdn.xitu.io/2019/3/12/1696fe7b24a9d22d?w=487&h=288&f=png&s=3652)

我们可以发现red块被green块遮住了，让我们来分析一下为什么？

发生变动的是red的父元素div，因为设置了`opacity: .99`，使得red的父元素创建了层叠上下文。那么现在的层叠上下文和层叠顺序是这个样子的:

 - html根层叠上下文
   - black普通block块，层叠顺序为3
   - red父元素层叠上下文，由opacity不等于1产生，层叠顺序为6(css3新属性不依赖z-index产生的层叠上下文的层叠顺序为6)
        - red层叠上下文，层叠顺序为7
   - green绝对定位块，无层叠上下文，层叠顺序为6
   - blue绝对定位块，无层叠上下文，层叠顺序为6
   
这样的话black，green，blue只和red的父元素比较层叠顺序了，而此时red父元素，green，blue的层叠顺序相同，按文档的顺序重叠，也就是后来居上，后面的覆盖前面的，因此产生了这样的效果。
